<?php

//PRUEBA PHP NUMERO 2

// AL INVOCAR LA URL http://ip-api.com/json/ MEDIANTE GET, SE RETORNA UN JSON CON LA INFORMACION RELATIVA A LA IP PUBLICA DESDE LA CUAL CONSULTA LA url 
// USANDO CURL, INVOQUE DICHA URL CON UNA IP CUALQUIERA
// EL JSON OBTENIDO, IMPRIMALO COMO ARRAY




?>